-- MySQL Script generated by MySQL Workbench
-- lun. 17 juil. 2017 16:56:58 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `content` INT NOT NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `name` CHAR(1) NOT NULL,
  `email` CHAR(1) NULL,
  `tweet_content` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_user_tweet_idx` (`tweet_content` ASC),
  CONSTRAINT `fk_user_tweet`
    FOREIGN KEY (`tweet_content`)
    REFERENCES `mydb`.`tweet` (`content`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `website_url` CHAR(1) NOT NULL,
  PRIMARY KEY (`website_url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_organization` (
  `user_name` CHAR(1) NOT NULL,
  `organization_website_url` CHAR(1) NOT NULL,
  PRIMARY KEY (`user_name`, `organization_website_url`),
  INDEX `fk_user_has_organization_organization1_idx` (`organization_website_url` ASC),
  INDEX `fk_user_has_organization_user1_idx` (`user_name` ASC),
  CONSTRAINT `fk_user_has_organization_user1`
    FOREIGN KEY (`user_name`)
    REFERENCES `mydb`.`user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_organization_organization1`
    FOREIGN KEY (`organization_website_url`)
    REFERENCES `mydb`.`organization` (`website_url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
